### PR TITLE
(mac compatibility) Update all backslash references to os.sep

### PR DESCRIPTION
**Pull request by demonbane**

### CODE REVIEW

**Comment by demonbane** [comment]
This gets EliteOCR working correctly on a Mac, after all of the dependencies are fixed. (which takes quite a bit of effort)

There are two known issues here:

* Building with `pyinstaller` succeeds, but the resulting binary isn't usable just yet. I noticed some `pyinstaller` related code in `make.py`, so that might be involved? (running `make.py` myself didn't really help much)
* There's an error with `tessdata` when trying to run this. I have to manually pass the `TESSDATA_PREFIX` environment variable and point it at the current directory to have it work correctly.

**Comment by seeebek** [comment]
make.py is just a helper script to generate windows binaries. It does not interfere with the rest ofthe code.
I need to check this and will merge it as soon as I can.

**Comment by demonbane** [comment]
I just added a helper script called `make.sh` that does most of the same things that `make.py` does, just on OSX. With this and the previous `TESSDATA_PREFIX` fix in place, I can now build fully working OSX images with `pyinstaller`.

I'm not 100% sure if these are fully portable yet because I suspect that homebrew used some weird build flags when compiling some of the required packages. This package runs fine on my 10.10.2 machine, but when tested on a 10.10.1 machine it crashes.

I have a build available here if anyone would like to give it a shot on their system. Just run `EliteOCR` inside the folder of the same name:

https://dl.dropboxusercontent.com/u/142407/EliteOCR.tar.gz

**Comment by beldougie** [comment]
I might pull your branch into my fork demonbane.. I will also test your Mac build. Cheers

**Pull request closed without merging**
